#!/usr/bin/env bash
# Self-host Google Fonts: fetch the exact woff2 subsets Google would serve and
# rewrite the @font-face src to local paths. Network runs in a container so
# nothing is installed on the host.
#
# Usage: fetch-fonts.sh <css_url> <font_dir> <url_prefix> <css_out>
#   css_url    the fonts.googleapis.com/css2 URL
#   font_dir   directory to save the .woff2 files into
#   url_prefix how the CSS should reference them (e.g. "fonts/" or "/fonts/")
#   css_out    path to write the rewritten @font-face CSS
set -euo pipefail

CSS_URL="$1"; FONT_DIR="$2"; URL_PREFIX="$3"; CSS_OUT="$4"
# A modern browser UA makes Google return woff2 (older UAs get ttf).
UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
CURL=(docker run --rm curlimages/curl:latest -s)

mkdir -p "$FONT_DIR"
css="$("${CURL[@]}" -A "$UA" "$CSS_URL")"

# Several @font-face blocks pointing at one file mean the URL asked for discrete
# weights (`wght@400;500`) of what is a variable font. Google then serves the
# same file for each of them, and every block caps the axis at its own weight —
# so a page asking for 600 gets synthetic bold smeared over the 500 glyphs, and
# 600 and 700 become indistinguishable. The panel shipped that way until
# 2026-08-17. Ask for a range (`wght@100..900`) and one block per subset covers
# the whole axis. Checked before anything is downloaded.
duplicated="$(printf '%s\n' "$css" | grep -oE 'src: *url\([^)]+\)' | sort | uniq -d | wc -l)"
if [ "$duplicated" -gt 0 ]; then
  {
    echo "ОТКАЗ: $duplicated файл(ов) объявлены по нескольку раз."
    echo "В адресе перечислены отдельные веса вариативного шрифта — каждый блок"
    echo "обрежет ось насыщенности на своём весе, и жирность станет поддельной."
    echo "Запросите диапазон, например wght@100..900, и повторите."
    echo "Адрес был: $CSS_URL"
  } >&2
  exit 1
fi

urls=$(printf '%s\n' "$css" | grep -oE 'https://fonts\.gstatic\.com/[^)]+\.woff2' | sort -u)
count=0
for u in $urls; do
  base="$(basename "$u")"
  "${CURL[@]}" "$u" -o - > "$FONT_DIR/$base"
  css="${css//$u/${URL_PREFIX}${base}}"
  count=$((count + 1))
done

# Provenance in the file itself: the CSS is generated, and the request that
# produced it used to live nowhere, so nobody could regenerate it correctly.
{
  echo "/* Generated by scripts/fetch-fonts.sh — do not edit by hand."
  echo "   Source: $CSS_URL"
  echo "   Regenerate: scripts/fetch-fonts.sh '$CSS_URL' '$FONT_DIR' '$URL_PREFIX' '$CSS_OUT' */"
  echo
  printf '%s\n' "$css"
} > "$CSS_OUT"
echo "Saved $count woff2 to $FONT_DIR; rewrote CSS -> $CSS_OUT"
