// GENERATED by scripts/design/themes-css.py from web/themes/<brand>/*.json — do not edit.
export type ThemeEntry = { id: string; name: string; scheme: "light" | "dark"; night?: string };
// The themes a person may choose, per brand (a file with "section": false is night-only).
export const THEMES: Record<string, ThemeEntry[]> = {
  "neighbro": [
    {"id": "light", "name": "Light", "scheme": "light", "night": "dark"},
    {"id": "dark", "name": "Dark", "scheme": "dark", "night": "dark"},
    {"id": "azure", "name": "Azure", "scheme": "light", "night": "dark-azure"},
    {"id": "crimson", "name": "Crimson", "scheme": "light", "night": "dark-crimson"},
    {"id": "mono", "name": "Mono", "scheme": "light", "night": "mono-dark"},
    {"id": "mono-dark", "name": "Mono dark", "scheme": "dark", "night": "mono-dark"},
    {"id": "violet", "name": "Violet", "scheme": "light", "night": "dark-violet"},
  ],
  "sosed": [
    {"id": "light", "name": "Light", "scheme": "light", "night": "dark"},
    {"id": "dark", "name": "Dark", "scheme": "dark", "night": "dark"},
    {"id": "amber", "name": "Amber", "scheme": "light", "night": "dark-amber"},
    {"id": "azure", "name": "Azure", "scheme": "light", "night": "dark-azure"},
    {"id": "carmine", "name": "Carmine", "scheme": "light", "night": "dark-carmine"},
    {"id": "mono", "name": "Mono", "scheme": "light", "night": "mono-dark"},
    {"id": "mono-dark", "name": "Mono dark", "scheme": "dark", "night": "mono-dark"},
    {"id": "turquoise", "name": "Turquoise", "scheme": "light", "night": "dark-turquoise"},
    {"id": "violet", "name": "Violet", "scheme": "light", "night": "dark-violet"},
  ],
};
// Every theme's page colour, night-only ones included: meta theme-color.
export const THEME_BG: Record<string, Record<string, string>> = {
  "neighbro": {"azure": "#e5e6e9", "crimson": "#e5e6e9", "dark": "#0b0b0c", "dark-azure": "#0b0b0c", "dark-crimson": "#0b0b0c", "dark-violet": "#0b0b0c", "light": "#e5e6e9", "mono": "#e6e6e6", "mono-dark": "#0b0b0b", "violet": "#e5e6e9"},
  "sosed": {"amber": "#ece4d8", "azure": "#ece4d8", "carmine": "#ece4d8", "dark": "#0d0b0a", "dark-amber": "#0d0b0a", "dark-azure": "#0d0b0a", "dark-carmine": "#0d0b0a", "dark-turquoise": "#0d0b0a", "dark-violet": "#0d0b0a", "light": "#ece4d8", "mono": "#e5e5e5", "mono-dark": "#0b0b0b", "turquoise": "#ece4d8", "violet": "#ece4d8"},
};
